--- 
engines: 
  csslint: 
    enabled: true
  duplication: 
    config: 
      languages: 
        - javascript
    enabled: true
  eslint: 
    channel: eslint-3
    enabled: true
  nodesecurity: 
    enabled: true
exclude_paths: 
  - spec/**/*
  - "**/vendor/**/*"
ratings: 
  paths: 
    - app/**
    - lib/**
    - "**.rb"
    - "**.go"
