sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    code_climate:
      repo_token: <>
after_succes:
  - npm run coverage
  - npm run codeclimate-test-reporter
